"""Decomposition table of the value of the forecast (Proposition 2) for the Supplementary Material.

    python tools/decomp_table.py paper/supp/tables_decomp_s3.tex

Reads the frozen record data/p1d/oracle_decomposition.json (report-weighted means, equal weights over the two dispersion
levels) and, for the solver-certified bound on G_Y, the registered oracle diagnostics in data/p1c_tables.md, section 3.
Every number is copied and rounded to two decimals; nothing is recomputed.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIGS = ("A", "A+staged", "B", "B+staged")
FAMILIES = (("sym1", r"$\sigma=1$"), ("sym2", r"$\sigma=2$"), ("sym4", r"$\sigma=4$"), ("opt2", "biased"),
            ("uninf", "uninf."))


def fmt(x):
    s = f"{x:+.2f}"
    if s in ("+0.00", "-0.00"):
        return "0.00"
    return s.replace("-", "$-$")


def certified():
    """{(config, family): 'mean; max'} of the certified room over the forecast-aware plan (p1c_tables.md, section 3)."""
    text = (ROOT / "data/p1c_tables.md").read_text(encoding="utf-8")
    sec = text.split("## 3. Oracle diagnostics", 1)[1].split("\n## ", 1)[0]
    out = {}
    for line in sec.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 4 and cells[0] in CONFIGS:
            m = re.match(r"([+\-]?[\d.]+);\s*([+\-]?[\d.]+)", cells[3])
            out[cells[0], cells[1]] = (float(m.group(1)), float(m.group(2)))
    return out


def main(out_path):
    dec = json.loads((ROOT / "data/p1d/oracle_decomposition.json").read_text(encoding="utf-8"))["decomposition"]
    cert = certified()
    rows = []
    for cfg in CONFIGS:
        for fam, name in FAMILIES:
            m = dec[f"{cfg}|{fam}"]["mean"]
            gap = m["V_true"] + m["G0"]
            share = "--" if fam == "uninf" else f"{100 * m['share_of_gap_closed']:.0f}\\%"
            c_mean, c_max = cert[cfg, fam]
            rows.append(" & ".join([cfg if fam == "sym1" else "", name, fmt(m["d_info"]), fmt(m["V_true"]),
                                    fmt(m["G0"]), fmt(m["R_Y"]), fmt(gap), share,
                                    f"{c_mean:.2f}; {c_max:.2f}"]) + r" \\")
        rows.append(r"\addlinespace")
    rows = rows[:-1]
    head = [
        "% Generated by tools/decomp_table.py from data/p1d/oracle_decomposition.json and data/p1c_tables.md section 3.",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Decomposition of the value of the forecast, $\Delta_{\mathrm{info}}=V_{\mathrm{true}}+G_0-G_Y$"
        r" (Proposition~\ref{prop:s-decomp}; registered run, $\Delta=0$; \$M). $V_{\mathrm{true}}=v_0-v_Y$ is the value to a"
        r" planner who knows the true law; $V_{\mathrm{true}}+G_0$ is the cost gap from the report-based no-forecast plan"
        r" to the true-law optimal forecast-aware plan, and the share is the part of that gap the forecast-aware plan"
        r" closes. The last column is the solver-certified upper bound on $G_Y$ (mean over cells; maximum).}",
        r"\label{tab:s-oracle}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}llrrrrrrr@{}}",
        r"\toprule",
        r"Configuration & Family & $\Delta_{\mathrm{info}}$ & $V_{\mathrm{true}}$ & $G_0$ & $G_Y$ &"
        r" $V_{\mathrm{true}}+G_0$ & Share & Certified $G_Y$ \\",
        r"\midrule",
    ]
    tail = [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    pathlib.Path(out_path).write_text("\n".join(head + rows + tail), encoding="utf-8")
    print(f"written {out_path}: {len(CONFIGS) * len(FAMILIES)} rows")


if __name__ == "__main__":
    main(sys.argv[1])
